// Package main is the entry point for the Lens cache-visibility sidecar.
// Always-on providers are imported here. Config-selected providers are
// imported by providers_gen.go, generated by lens-build from lens.yaml.
package main

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/Vedanshu7/lens/internal/agent"

	// Always-on providers — included in every binary regardless of config.
	_ "github.com/Vedanshu7/lens/internal/observability/noop"
	_ "github.com/Vedanshu7/lens/internal/observability/prometheus"
	_ "github.com/Vedanshu7/lens/internal/observability/sql"
	_ "github.com/Vedanshu7/lens/internal/observability/stdout"
	_ "github.com/Vedanshu7/lens/internal/observability/webhook"
	_ "github.com/Vedanshu7/lens/internal/persistence/memory"
	_ "github.com/Vedanshu7/lens/internal/persistence/redis"
	_ "github.com/Vedanshu7/lens/internal/target/http"
)

func main() {
	cfg := agent.LoadConfig()

	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: agent.ParseLogLevel(cfg.LogLevel),
	})))

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	a := agent.New(cfg)

	srv := &http.Server{
		Addr:         cfg.BindAddr + ":" + cfg.Port,
		Handler:      a.Routes(),
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}
	go func() {
		slog.Info("lens agent listening", "port", cfg.Port)
		if err := srv.ListenAndServe(); err != http.ErrServerClosed {
			slog.Error("http server error", "err", err)
		}
	}()

	go a.Connect(ctx)

	<-ctx.Done()
	slog.Info("shutting down")
	a.Shutdown(context.Background())

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		slog.Error("shutdown error", "err", err)
	}
}
