// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/proto/lens.proto

package lensv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_internal_proto_lens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_lens_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvalidateRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *InvalidateRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type InvalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_internal_proto_lens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_lens_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidateResponse) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *InvalidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvalidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_internal_proto_lens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_lens_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_internal_proto_lens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_lens_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_internal_proto_lens_proto protoreflect.FileDescriptor

const file_internal_proto_lens_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/lens.proto\x12\alens.v1\"Y\n" +
	"\x11InvalidateRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\"`\n" +
	"\x12InvalidateResponse\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"&\n" +
	"\n" +
	"GetRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"B\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode2\x84\x01\n" +
	"\tLensAgent\x12E\n" +
	"\n" +
	"Invalidate\x12\x1a.lens.v1.InvalidateRequest\x1a\x1b.lens.v1.InvalidateResponse\x120\n" +
	"\x03Get\x12\x13.lens.v1.GetRequest\x1a\x14.lens.v1.GetResponseB0Z.github.com/Vedanshu7/lens/internal/proto/lensv1b\x06proto3"

var (
	file_internal_proto_lens_proto_rawDescOnce sync.Once
	file_internal_proto_lens_proto_rawDescData []byte
)

func file_internal_proto_lens_proto_rawDescGZIP() []byte {
	file_internal_proto_lens_proto_rawDescOnce.Do(func() {
		file_internal_proto_lens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_lens_proto_rawDesc), len(file_internal_proto_lens_proto_rawDesc)))
	})
	return file_internal_proto_lens_proto_rawDescData
}

var file_internal_proto_lens_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_lens_proto_goTypes = []any{
	(*InvalidateRequest)(nil),  // 0: lens.v1.InvalidateRequest
	(*InvalidateResponse)(nil), // 1: lens.v1.InvalidateResponse
	(*GetRequest)(nil),         // 2: lens.v1.GetRequest
	(*GetResponse)(nil),        // 3: lens.v1.GetResponse
}
var file_internal_proto_lens_proto_depIdxs = []int32{
	0, // 0: lens.v1.LensAgent.Invalidate:input_type -> lens.v1.InvalidateRequest
	2, // 1: lens.v1.LensAgent.Get:input_type -> lens.v1.GetRequest
	1, // 2: lens.v1.LensAgent.Invalidate:output_type -> lens.v1.InvalidateResponse
	3, // 3: lens.v1.LensAgent.Get:output_type -> lens.v1.GetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_lens_proto_init() }
func file_internal_proto_lens_proto_init() {
	if File_internal_proto_lens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_lens_proto_rawDesc), len(file_internal_proto_lens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_lens_proto_goTypes,
		DependencyIndexes: file_internal_proto_lens_proto_depIdxs,
		MessageInfos:      file_internal_proto_lens_proto_msgTypes,
	}.Build()
	File_internal_proto_lens_proto = out.File
	file_internal_proto_lens_proto_goTypes = nil
	file_internal_proto_lens_proto_depIdxs = nil
}
