// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: internal/proto/lens.proto

package lensv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LensAgent_Invalidate_FullMethodName = "/lens.v1.LensAgent/Invalidate"
	LensAgent_Get_FullMethodName        = "/lens.v1.LensAgent/Get"
)

// LensAgentClient is the client API for LensAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LensAgentClient interface {
	Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type lensAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewLensAgentClient(cc grpc.ClientConnInterface) LensAgentClient {
	return &lensAgentClient{cc}
}

func (c *lensAgentClient) Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateResponse)
	err := c.cc.Invoke(ctx, LensAgent_Invalidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lensAgentClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, LensAgent_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LensAgentServer is the server API for LensAgent service.
// All implementations must embed UnimplementedLensAgentServer
// for forward compatibility.
type LensAgentServer interface {
	Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedLensAgentServer()
}

// UnimplementedLensAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLensAgentServer struct{}

func (UnimplementedLensAgentServer) Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedLensAgentServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLensAgentServer) mustEmbedUnimplementedLensAgentServer() {}
func (UnimplementedLensAgentServer) testEmbeddedByValue()                   {}

// UnsafeLensAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LensAgentServer will
// result in compilation errors.
type UnsafeLensAgentServer interface {
	mustEmbedUnimplementedLensAgentServer()
}

func RegisterLensAgentServer(s grpc.ServiceRegistrar, srv LensAgentServer) {
	// If the following call panics, it indicates UnimplementedLensAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LensAgent_ServiceDesc, srv)
}

func _LensAgent_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensAgentServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LensAgent_Invalidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensAgentServer).Invalidate(ctx, req.(*InvalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LensAgent_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensAgentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LensAgent_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensAgentServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LensAgent_ServiceDesc is the grpc.ServiceDesc for LensAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LensAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lens.v1.LensAgent",
	HandlerType: (*LensAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invalidate",
			Handler:    _LensAgent_Invalidate_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LensAgent_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/lens.proto",
}
