// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/proto/target.proto

package targetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetInfoRequest) Reset() {
	*x = TargetInfoRequest{}
	mi := &file_internal_proto_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetInfoRequest) ProtoMessage() {}

func (x *TargetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetInfoRequest.ProtoReflect.Descriptor instead.
func (*TargetInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{0}
}

type TargetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetInfoResponse) Reset() {
	*x = TargetInfoResponse{}
	mi := &file_internal_proto_target_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetInfoResponse) ProtoMessage() {}

func (x *TargetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetInfoResponse.ProtoReflect.Descriptor instead.
func (*TargetInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{1}
}

func (x *TargetInfoResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TargetInfoResponse) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

type TargetInvalidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload is the JSON-encoded invalidation body, e.g. {"pattern":"key:*"}.
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetInvalidateRequest) Reset() {
	*x = TargetInvalidateRequest{}
	mi := &file_internal_proto_target_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetInvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetInvalidateRequest) ProtoMessage() {}

func (x *TargetInvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetInvalidateRequest.ProtoReflect.Descriptor instead.
func (*TargetInvalidateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{2}
}

func (x *TargetInvalidateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TargetInvalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetInvalidateResponse) Reset() {
	*x = TargetInvalidateResponse{}
	mi := &file_internal_proto_target_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetInvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetInvalidateResponse) ProtoMessage() {}

func (x *TargetInvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetInvalidateResponse.ProtoReflect.Descriptor instead.
func (*TargetInvalidateResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{3}
}

type TargetGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetGetRequest) Reset() {
	*x = TargetGetRequest{}
	mi := &file_internal_proto_target_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGetRequest) ProtoMessage() {}

func (x *TargetGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGetRequest.ProtoReflect.Descriptor instead.
func (*TargetGetRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{4}
}

func (x *TargetGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TargetGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// body is the raw JSON response body from the application cache.
	Body          []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetGetResponse) Reset() {
	*x = TargetGetResponse{}
	mi := &file_internal_proto_target_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetGetResponse) ProtoMessage() {}

func (x *TargetGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetGetResponse.ProtoReflect.Descriptor instead.
func (*TargetGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{5}
}

func (x *TargetGetResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type TargetKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Limit         string                 `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        string                 `protobuf:"bytes,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetKeysRequest) Reset() {
	*x = TargetKeysRequest{}
	mi := &file_internal_proto_target_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetKeysRequest) ProtoMessage() {}

func (x *TargetKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetKeysRequest.ProtoReflect.Descriptor instead.
func (*TargetKeysRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{6}
}

func (x *TargetKeysRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *TargetKeysRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *TargetKeysRequest) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type TargetKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// body is the raw JSON response body containing the key list.
	Body          []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetKeysResponse) Reset() {
	*x = TargetKeysResponse{}
	mi := &file_internal_proto_target_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetKeysResponse) ProtoMessage() {}

func (x *TargetKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_target_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetKeysResponse.ProtoReflect.Descriptor instead.
func (*TargetKeysResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_target_proto_rawDescGZIP(), []int{7}
}

func (x *TargetKeysResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_internal_proto_target_proto protoreflect.FileDescriptor

const file_internal_proto_target_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/target.proto\x12\x0elens.target.v1\"\x13\n" +
	"\x11TargetInfoRequest\"J\n" +
	"\x12TargetInfoResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\"3\n" +
	"\x17TargetInvalidateRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x1a\n" +
	"\x18TargetInvalidateResponse\"$\n" +
	"\x10TargetGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\x11TargetGetResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\"[\n" +
	"\x11TargetKeysRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\tR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\tR\x06offset\"(\n" +
	"\x12TargetKeysResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body2\xd7\x02\n" +
	"\n" +
	"LensTarget\x12M\n" +
	"\x04Info\x12!.lens.target.v1.TargetInfoRequest\x1a\".lens.target.v1.TargetInfoResponse\x12_\n" +
	"\n" +
	"Invalidate\x12'.lens.target.v1.TargetInvalidateRequest\x1a(.lens.target.v1.TargetInvalidateResponse\x12J\n" +
	"\x03Get\x12 .lens.target.v1.TargetGetRequest\x1a!.lens.target.v1.TargetGetResponse\x12M\n" +
	"\x04Keys\x12!.lens.target.v1.TargetKeysRequest\x1a\".lens.target.v1.TargetKeysResponseB3Z1github.com/Vedanshu7/lens/internal/proto/targetv1b\x06proto3"

var (
	file_internal_proto_target_proto_rawDescOnce sync.Once
	file_internal_proto_target_proto_rawDescData []byte
)

func file_internal_proto_target_proto_rawDescGZIP() []byte {
	file_internal_proto_target_proto_rawDescOnce.Do(func() {
		file_internal_proto_target_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_target_proto_rawDesc), len(file_internal_proto_target_proto_rawDesc)))
	})
	return file_internal_proto_target_proto_rawDescData
}

var file_internal_proto_target_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_target_proto_goTypes = []any{
	(*TargetInfoRequest)(nil),        // 0: lens.target.v1.TargetInfoRequest
	(*TargetInfoResponse)(nil),       // 1: lens.target.v1.TargetInfoResponse
	(*TargetInvalidateRequest)(nil),  // 2: lens.target.v1.TargetInvalidateRequest
	(*TargetInvalidateResponse)(nil), // 3: lens.target.v1.TargetInvalidateResponse
	(*TargetGetRequest)(nil),         // 4: lens.target.v1.TargetGetRequest
	(*TargetGetResponse)(nil),        // 5: lens.target.v1.TargetGetResponse
	(*TargetKeysRequest)(nil),        // 6: lens.target.v1.TargetKeysRequest
	(*TargetKeysResponse)(nil),       // 7: lens.target.v1.TargetKeysResponse
}
var file_internal_proto_target_proto_depIdxs = []int32{
	0, // 0: lens.target.v1.LensTarget.Info:input_type -> lens.target.v1.TargetInfoRequest
	2, // 1: lens.target.v1.LensTarget.Invalidate:input_type -> lens.target.v1.TargetInvalidateRequest
	4, // 2: lens.target.v1.LensTarget.Get:input_type -> lens.target.v1.TargetGetRequest
	6, // 3: lens.target.v1.LensTarget.Keys:input_type -> lens.target.v1.TargetKeysRequest
	1, // 4: lens.target.v1.LensTarget.Info:output_type -> lens.target.v1.TargetInfoResponse
	3, // 5: lens.target.v1.LensTarget.Invalidate:output_type -> lens.target.v1.TargetInvalidateResponse
	5, // 6: lens.target.v1.LensTarget.Get:output_type -> lens.target.v1.TargetGetResponse
	7, // 7: lens.target.v1.LensTarget.Keys:output_type -> lens.target.v1.TargetKeysResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_target_proto_init() }
func file_internal_proto_target_proto_init() {
	if File_internal_proto_target_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_target_proto_rawDesc), len(file_internal_proto_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_target_proto_goTypes,
		DependencyIndexes: file_internal_proto_target_proto_depIdxs,
		MessageInfos:      file_internal_proto_target_proto_msgTypes,
	}.Build()
	File_internal_proto_target_proto = out.File
	file_internal_proto_target_proto_goTypes = nil
	file_internal_proto_target_proto_depIdxs = nil
}
