// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: internal/proto/target.proto

package targetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LensTarget_Info_FullMethodName       = "/lens.target.v1.LensTarget/Info"
	LensTarget_Invalidate_FullMethodName = "/lens.target.v1.LensTarget/Invalidate"
	LensTarget_Get_FullMethodName        = "/lens.target.v1.LensTarget/Get"
	LensTarget_Keys_FullMethodName       = "/lens.target.v1.LensTarget/Keys"
)

// LensTargetClient is the client API for LensTarget service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LensTarget is implemented by the application service. The Lens sidecar
// calls these RPCs instead of the default HTTP endpoints when the
// target provider is set to "grpc".
type LensTargetClient interface {
	// Info returns the service identity (name and instance ID).
	Info(ctx context.Context, in *TargetInfoRequest, opts ...grpc.CallOption) (*TargetInfoResponse, error)
	// Invalidate removes cache entries matching the given payload.
	Invalidate(ctx context.Context, in *TargetInvalidateRequest, opts ...grpc.CallOption) (*TargetInvalidateResponse, error)
	// Get returns the current value of a cache key.
	Get(ctx context.Context, in *TargetGetRequest, opts ...grpc.CallOption) (*TargetGetResponse, error)
	// Keys returns cache key metadata, with optional filtering.
	Keys(ctx context.Context, in *TargetKeysRequest, opts ...grpc.CallOption) (*TargetKeysResponse, error)
}

type lensTargetClient struct {
	cc grpc.ClientConnInterface
}

func NewLensTargetClient(cc grpc.ClientConnInterface) LensTargetClient {
	return &lensTargetClient{cc}
}

func (c *lensTargetClient) Info(ctx context.Context, in *TargetInfoRequest, opts ...grpc.CallOption) (*TargetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetInfoResponse)
	err := c.cc.Invoke(ctx, LensTarget_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lensTargetClient) Invalidate(ctx context.Context, in *TargetInvalidateRequest, opts ...grpc.CallOption) (*TargetInvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetInvalidateResponse)
	err := c.cc.Invoke(ctx, LensTarget_Invalidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lensTargetClient) Get(ctx context.Context, in *TargetGetRequest, opts ...grpc.CallOption) (*TargetGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetGetResponse)
	err := c.cc.Invoke(ctx, LensTarget_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lensTargetClient) Keys(ctx context.Context, in *TargetKeysRequest, opts ...grpc.CallOption) (*TargetKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetKeysResponse)
	err := c.cc.Invoke(ctx, LensTarget_Keys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LensTargetServer is the server API for LensTarget service.
// All implementations must embed UnimplementedLensTargetServer
// for forward compatibility.
//
// LensTarget is implemented by the application service. The Lens sidecar
// calls these RPCs instead of the default HTTP endpoints when the
// target provider is set to "grpc".
type LensTargetServer interface {
	// Info returns the service identity (name and instance ID).
	Info(context.Context, *TargetInfoRequest) (*TargetInfoResponse, error)
	// Invalidate removes cache entries matching the given payload.
	Invalidate(context.Context, *TargetInvalidateRequest) (*TargetInvalidateResponse, error)
	// Get returns the current value of a cache key.
	Get(context.Context, *TargetGetRequest) (*TargetGetResponse, error)
	// Keys returns cache key metadata, with optional filtering.
	Keys(context.Context, *TargetKeysRequest) (*TargetKeysResponse, error)
	mustEmbedUnimplementedLensTargetServer()
}

// UnimplementedLensTargetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLensTargetServer struct{}

func (UnimplementedLensTargetServer) Info(context.Context, *TargetInfoRequest) (*TargetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedLensTargetServer) Invalidate(context.Context, *TargetInvalidateRequest) (*TargetInvalidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedLensTargetServer) Get(context.Context, *TargetGetRequest) (*TargetGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLensTargetServer) Keys(context.Context, *TargetKeysRequest) (*TargetKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Keys not implemented")
}
func (UnimplementedLensTargetServer) mustEmbedUnimplementedLensTargetServer() {}
func (UnimplementedLensTargetServer) testEmbeddedByValue()                    {}

// UnsafeLensTargetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LensTargetServer will
// result in compilation errors.
type UnsafeLensTargetServer interface {
	mustEmbedUnimplementedLensTargetServer()
}

func RegisterLensTargetServer(s grpc.ServiceRegistrar, srv LensTargetServer) {
	// If the following call panics, it indicates UnimplementedLensTargetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LensTarget_ServiceDesc, srv)
}

func _LensTarget_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensTargetServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LensTarget_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensTargetServer).Info(ctx, req.(*TargetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LensTarget_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetInvalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensTargetServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LensTarget_Invalidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensTargetServer).Invalidate(ctx, req.(*TargetInvalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LensTarget_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensTargetServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LensTarget_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensTargetServer).Get(ctx, req.(*TargetGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LensTarget_Keys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LensTargetServer).Keys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LensTarget_Keys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LensTargetServer).Keys(ctx, req.(*TargetKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LensTarget_ServiceDesc is the grpc.ServiceDesc for LensTarget service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LensTarget_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lens.target.v1.LensTarget",
	HandlerType: (*LensTargetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _LensTarget_Info_Handler,
		},
		{
			MethodName: "Invalidate",
			Handler:    _LensTarget_Invalidate_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LensTarget_Get_Handler,
		},
		{
			MethodName: "Keys",
			Handler:    _LensTarget_Keys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/target.proto",
}
